baseURL = 'https://tabasku.github.io/'
languageCode = 'en-us'
title = 'Joni's blog'
theme = 'terminal'

[taxonomies]
tag = 'tags'

[params]
    author = "Joni Kurunsaari"
    description = "Blogging about stuff I want to learn and remember"

    # Terminal theme settings
    contentTypeName = "posts"
    showMenuItems = 3
    fullWidthTheme = false
    centerTheme = false

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/jonikurunsaari/"

[[params.social]]
name = "github"
url = "https://github.com/tabasku"

# Main menu pages
[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about"

[[menu.main]]
identifier = "library"
name = "Library"
url = "/library"


# Syntax highlight on code blocks
# Required for Terminal theme and Chroma highlighting
[markup]
[markup.highlight]
noClasses = false

# Deploy settings

[[deployment.matchers]]
pattern = "^.+\\.(js|css|svg|ttf|woff2)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = true

[[deployment.matchers]]
pattern = "^.+\\.(png|jpg|gif|webp)$"
cacheControl = "max-age=31536000, no-transform, public"
gzip = false