baseURL = 'https://tabasku.github.io/'
languageCode = 'en-us'
title = 'Joni’s blog'
theme = 'basic'

[params]
    author = "Joni Kurunsaari"
    description = "Blogging about stuff I want to learn and remember"
    
[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
    [[menu.main]]
        name = "Posts"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 3
